[Feature] EmployeeManager 클래스 초기 구현
sungkj/Developers pull request #8
Opened 2022-03-03 09:16 UTC by sungkj

- Input, Output 클래스 초기 구현
- EmployeeManager 클래스 초기 구현
- 파일 입/출력을 통한 동작 확인
   : del, mod 가 아직 동작하지 않아 Solution 파일과 다른 부분 발생함
   : Solution 파일과 비교 결과 "SCH,NONE" 이 출력되야 하는데 "NONE" 으로 출력됨

2022-03-03 23:48 UTC, KimJoohwan commented on Developers/employee_manager.cpp
> +			outputStrs_.push_back(command->execute(commandStr));
command->execute(commandStr)을 동일한게 2번 실행하는것 같은데, 
1번으로 가능하지 않을까요?

2022-03-04 00:00 UTC, iced-espresso requested changes

2022-03-04 00:00 UTC, iced-espresso commented on Developers/employee_manager.cpp
> +		if (!outputStr.empty()) {
저도 동일한 의견드립니다~
2번 호출하게 된다면 다른 output text가 출력될 것 같습니다.

2022-03-04 00:01 UTC, SSLeeJY commented on Developers/employee_manager.cpp
> +			outputStrs_.push_back(command->execute(commandStr));
두번 돌게되면서 결과값이 달라질 가능성도 있어보입니다.

2022-03-04 00:09 UTC, sungkj commented on Developers/employee_manager.cpp
> +			outputStrs_.push_back(command->execute(commandStr));
앗 그러네요. 결과에도 영향을 주는 부분이네요. 수정했습니다.

2022-03-04 00:09 UTC, sungkj commented on Developers/employee_manager.cpp
> +		if (!outputStr.empty()) {
수정했습니다.

2022-03-04 00:19 UTC, SSLeeJY approved these changes
리뷰 내용 수정 확인 완료하였습니다.

2022-03-04 00:20 UTC, jkfd11 approved these changes

2022-03-04 00:32 UTC, KimJoohwan approved these changes

2022-03-04 00:34 UTC, merged